settings:
  title: 'Status Page'
  url: 'https://status.cutenico.best' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Cutenico-Blog # unique identifier
    name: blog.cutenico.best
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://cutenico.best/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: Cutenico-Offer
    name: offer.cutenico.best
    description: 'Built for anything connected to the Internet.'
    url: 'https://offer.cutenico.best'
    method: GET
    expectStatus: 200

  - id: Cutenico-Speedtest
    name: Custom Speedtest of Ookla
    url: 'https://speed.cutenico.best/'
    method: GET
    expectStatus: 200
